### PR TITLE
Blog

### PR DESCRIPTION
**Pull request by calej17**
## Blog

This branch sets up the blog main page (posts list) and the single post page. It incorporates the blog post overview from Nathan's `post-overview` branch. 

-
**This is not ready for review.**

### CODE REVIEW

**Comment by calej17** [comment]
@jonmspencer I think this is ready for review.

**Comment by jonmspencer** [comment]
@calej17 on the single blog pist let's allow for a post featured image in the hero if it is present. If it's not present, let's default to the blog page featured image. Thanks.

**Comment by calej17** [comment]
@jonmspencer Done. Ready for review again.

**Comment by jonmspencer** [comment]
@calej17 looking good. Merging up!

**Pull request merged**
