### PR TITLE
Post Overview: Structure and Styles

### PR DESCRIPTION
**Pull request by nathantrz**
This pull request adds a fully-responsive Post Overview partial.

### CODE REVIEW

**Comment by nathantrz** [comment]
@jonmspencer I got this as for as I can, so it's ready for review. 👍

**Comment by jonmspencer** [comment]
@nathantrz this overall looks very nice! I noticed a bunch of areas wehre pixel values are used. Please change every instance to an em, so that we can scale this module as a whole, then tag me again. Thanks!

**Comment by nathantrz** [comment]
@jonmspencer I made those changes. Ready for review and merge.

**Comment by calej17** [comment]
I've extracted the post overview components from this branch and incorporated them into the Blog branch PR ( #27 ). Closing.

**Pull request closed without merging**
