### PR TITLE
Fonts: Roboto

### PR DESCRIPTION
**Pull request by nathantrz**
This pull request adds Roboto font files to assets/fonts.

### CODE REVIEW

**Comment by nathantrz** [comment]
@jonmspencer Ready for review and merge

**Comment by jonmspencer** [comment]
@nathantrz I noticed some naing inconsitencies, like most fonts were nameed `R-B`, but the main font was named `robotoregular`.  I named each font `Roboto` then with any Modifier like `-B`. For projects that clients may see code, I think it'll be important for us to more clearly name fonts. Actually, we probably should just get in the habit of it becuse it's good practice. 

Also - I noticed the `font-stack` in the `style.scss` has an incorrect stack. It's calling proxima nova, which will cause server errors since that font doesn't exist here. Mind adding a correct stack? 

The stak should be the primary font used, follwed by a backup, followed by web default backups. 

Thanks!

**Comment by nathantrz** [comment]
@jonmspencer Ready for review and merge! Thanks

**Comment by jonmspencer** [comment]
@nathantrz looks good. Merging up!

**Pull request merged**
